dist: xenial
branches:
  only:
  - master
language: ruby
jobs:
  include:
  - stage: Build_lib
    name: Test Lib and Deploy
    script:
    - gem install bundler
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/ && bundle install
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/helpers/ &&
      ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/rest-client/
      && ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/outreach-s3/
      && ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/release/ &&
      ruby unit-tests.rb
    before_deploy:
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem
    after_success:
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems
    - git tag 1.0.$TRAVIS_BUILD_NUMBER
    - git push origin --tags
stages:
- Build_lib
deploy:
  provider: rubygems
  api_key: $RUBY_TOKEN
  gem: outreach_gem
  on:
    branch: master
