dist: xenial
branches:
  only:
  - master
language: ruby
jobs:
  include:
  - stage: Build_lib
    name: Test Lib and Deploy
    script:
    - gem install bundler
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/ && bundle install
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/helpers/ &&
      ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/rest-client/
      && ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/outreach-s3/
      && ruby unit-tests.rb
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem/tests/release/ &&
      ruby unit-tests.rb
    before_deploy:
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems/outreach_gem
    after_success:
    - cd $HOME/build/AES-Outreach/Outreach-Ruby-Gems
    - git tag 1.0.$TRAVIS_BUILD_NUMBER
    - git push origin --tags
stages:
- Build_lib
notifications:
  slack:
    secure: dmA3ZY4SM4weu0qLz4M+J5gmgVhWJ2qmACIeW79uDlP+fmi9GwsRJGeH06eLVxcLWObqQUC5VxYMut3FH6+eCwRdwT4EIZ+0he8SOFUd7DAFyAF1PqeN/fILLxpu5RMqxGT1bH8akzS/ihCxyyWAaU/Hh8tN4pO+hizydvOLLlUYCvolI3pfyMtYTqW/K/iOnv/63atF6aKN55u2j5Qjr8SPav4gA0HYKR4PnT5ib+CgVeJI0RLAFJ9vIVmUAXyrLWUlw5Du1/aJ1PHr+X5mibSxi1kyhErtAAyEk8MHpfciWLOboUOfL1K87orvRvy4AaF1ki/EpF4+uXtyG/2s34t664GW5Knf8zaRPouj2eEzWIfgktIrRAwSv13B65WzYF+NZ1Jygdn+lCuG9VTAzQpaQJBCUWZ8hSafW/i46rHy+Ub6xql1oSsSle4sO0yod/lcRLBwmwcPfS528Pabrn0CXwFuglEyiKpa0W7kf+hToj0PiD7zqEEi4kPNns18vP1Etm5hFBthMHluzEi4J5xCBzhKCHTYGno8qI/1UXNFHQ2sxfBU5Y922uVX0zqEV6ZpHDrUkpZoKchc6Y42IliqyVyZpNJxqfRHOu7sGvVYHlEJeQD4sZA5btBpwQ5wxvtB9r0ft1oWRRc84Lk4KbqOeIZ5gFpPlCmAv95eINg=
  email:
    recipients:
    - patrique.legault@uottawa.ca
deploy:
  provider: rubygems
  api_key:
    secure: DRORbRNO1QlmauwRRJQK377nSaSwg8oDM4wNykZNT5a4079G3tJ/NrKL+p2V2pk++WtAIHKJv+dmyiTu/k1PT/GfdCZC5t/Ae05+UfGbyBVrNxWnHY8lKTEWDDoFPDB1azHTJNmpxtaFVg/gGUVxaFjlpct+41PWz1WD72Or0pMQ02C2RPw+S7Hux6opkIspwc5VqBbcUUSpAxKeH2G+ffK3PmHTOuE6Kg/roswAIqJqDDtKjz5/9PmCCVT+5TKF9iTtLumDWxPrPWXbwf6cf3iBU1M4WE7jncH4CQUQOvkecyHiu5MXR8RkEXVfAikbiKWpouyz35KscD2J5PD4S4QdRn0uWZzexptkftWGnDIvl7Pid9FkBsHmki3/7B5wlwOLtK2CLNLFatVcEYCjF28fa9E516spyL4iVtfiQf+MzC/jZe8KL1GBnK0RLzDfG8RpXerCh3yHf3j1er/4Icgk97NmvXI4eWuDMM6UrdYwf7019g46ZSzitz0Bjr7/UGLeDtOpLvbgL93+/hL1wl07Fe2FNzx01j2blgUIBdSIdJ6lkYx/kFfLA1gBtkmoc3UPshsJBkg/dX1m6lqmTQA2X/IGAoe7cPWu8CNDrmZwKgx2dCcfAGtcm8db3lmv5DBJ3IDoMydD8Cxz15wgr41yMTgSu9YqGU2+K+nHwrk=
  gem: outreach_gem
  on:
    branch: master
env:
  global:
  - secure: FtFklUgugvEfC902sohF5hCfI7q9QiOpjIf88T+xGxspw2m9ed3yNtElVICtIik1jZZ5cyuQ0fXF8mX8JLc6MjjS++l1byuSnHC2vyJkDPW15jZ7aGOQbLQx9jA2j9N6rt3jZWzb7YfJUa014DGpB+uMULZEfZ7I6UnzvPJeib1uTfHl6rp05hA5+oXBq2kfA5bankbDpULizMeUBGJBoDSyfwx5ztrLIZtEsQqD1w+KloNqu8cmwd2ySCEhZ30331VH32kyYDjt69IQgW8Tvwg57YYwBngYS1iRCcMjSJgHhPtS7b1UytyGleygTbtGVkKFh3/0zNwr9sDY1C8/23iv4j6OQD4whiseWEghv2ySObQQl8zX307+PqHZ7Vo9Yc5yhObcRzEird3evE1exiclFu75BTeQySPlDJbmokJXXCB2unCIAzetEhNlNInGd/O4YrHae2XlJ+tV5e0PZnMVpLhMgTsWCwBqFJ7p0f4fMSMpJGGNYdUh497YPCe8+rsFrCQ+4X5QIJxdXBi4m3odna1CS5nD3VradjRHSXvXXhXP1okkY6SnIZ/mAa9By7QQm+095bze3vX/LC6sB1gOczWMxEmzf6iDZsUFsc5QV+U58iVKrHiBhvy/tPz/TLjz/XcI2yU+KHfXZ6iqZC6yL8hTLFHzDs43pcx/Q9Y=
  - secure: NbeSMyE6Q2iyL3IAA3WOtJ7mAWLnfn7hagUx5JQ8l+Kg8RhOhHd0CbHO88zTWUYoBMuypzB14OTaA2GypdpS/a5Rg2VnLjGrZrpGrDGx61anS3U7J4tlv6x+xeiAAO84/rLKgL+BTTbp1lCYodB+w9GLxD72bXh+BQDBMy/kItL6DpZiRUMvBKnBREVJTCTQTjb014T8uIcWTwzHL5/xTv9hf+2l88yaWPYjZe9fpGfbMoGSjwEWZIxCO/+VLDdLrrD7ZuSqXIvgsfyJE2Hz0gj8errPahb7VShJjck3E4OtjQ7V+F7yvod2wBz3PiM3nfVaG9prgYDPd++9g4iI5fblcumlMz2sr5awH8nQ9RElKQGQLCBJP6UdYPsTijXV2zhAE8RIiicN3Wk+x2Cte01+YlxfddCBL2EIQwJWIrPI0kn8HKzlCYYlhKW1DLgEXQUQua8tbphWixZxH5s0Wii6Ed4AlNl04dV0a/mPrwbWqNafzfBqC/7QfQ5sKu1MAt5CVWOiXubfqEmf74p6BU/Jbk7W+mLkqKHALOjfA+yHN0RGmFzu0A7kV7RXV1/pQB3NXCTRBTMc9iZiEjHgYOCMReCazkzXF22wJ7oojF8c5CqOBJt6+38vajB8E2gPHoAtzcOFKF4JnSO0EVrOPdB7J8kCtBLvE7M0Pzc8LuU=
  - secure: DKMUDId4TguoHpRpimuHYXoj6uaPM26Lxj6QIm0CL06Vkx22yqk2kJb5hMF8terXXL23Uq83fXZo4lJwi6x6culpjFRHNiTZu/nGFY+/lY+t1BAAMSHj1LcRAYMGyydrqXZtEiGZqfIyEinsieyqKglFHVu75lHQ8Q/dNDeQj038hkQ0o5x/M9BmEXndgMohDMpwdPkcaVddWlVDdE2xrROjXNLV0E5iSQ1AVPNGRNR33+u4XLfIcBmvbaK0GmROKAtN381ZjutChfwUumQLxKk98GGVSZHvJB5ES5W6aL7N56XJiT47LDFR+cepfYaExCYC8m8lpWzacEcPiqVVQFg6WKWa3jkXS2RC6qw3OKA3NIxgARyLsca8s2P1tPLKPh3WUR1xR1YH1U1HmOvJWBnxNvSSxW/3FXtu+WXW48HJp+ZhoXsqkcUPodXhi9rcv2VMO8Ffr5r8LJYg2fSgKOgb3onZx/7400EJstCHgFgx2nbRpfD+97P/vNdHgZZtmEjtqLnTw4eiqsXHjniMAavxLXMvxuY1+Gx29hQF/slw8+S67hvcilOSDq/RAYSiDAtYFCuIfbBP+slzXRGMT8s4FXokPM8cuWL38UdpUkEySF4uDKJ3RlBqw//+b47vyEiB2GlYT5A2+KxuGVmIHAd6XAXNZ+74CJunNTAITLQ=
